work-connect/src/main/java/com/cy/work/connect/web/common/ActivationItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.connect.web.common;

import com.cy.work.connect.web.common.setting.ActivationItemSetting;
import java.io.Serializable;
import java.util.List;
import javax.faces.model.SelectItem;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 狀態Item Bean
 *
 * @author brain0925_liao
 */
@Controller
@Scope("request")
public class ActivationItemBean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 7783246481634708463L;

    /**
     * 取得狀態SelectItems
     */
    public List<SelectItem> getActivationItems() {
        return ActivationItemSetting.getActivationItems();
    }
}

work-connect/src/main/java/com/cy/work/connect/web/common/CompanyBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.connect.web.common;

import com.cy.commons.vo.Org;
import com.cy.work.common.cache.WkOrgCache;
import com.cy.work.common.cache.WkUserCache;
import java.io.Serializable;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

import javax.faces.model.SelectItem;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 目的公司Item Bean
 *
 * @author jimmy_chou
 */
@Controller
@Scope("view")
public class CompanyBean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 6251311624674623448L;

    /**
     * 取得來源公司SelectItems
     */
    public List<SelectItem> getCompanyItems() {
        return  WkUserCache.getInstance().findSecAuth()
                .stream()
                // 轉為 Org 資料
                .map(secAuth -> WkOrgCache.getInstance().findById(secAuth.getCompId()))
                .filter(comp -> comp != null)
                // 排序
                .sorted(Comparator.comparing(Org::getSeqNumber))
                // 轉為 SelectItem
                .map(comp -> new SelectItem(comp.getSid(), comp.getName()))
                .collect(Collectors.toList());
    }
}

work-connect/src/main/java/com/cy/work/connect/web/common/SourceCompanyBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.connect.web.common;

import com.cy.work.connect.web.common.setting.SourceCompanySetting;
import java.io.Serializable;
import java.util.List;
import javax.faces.model.SelectItem;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 來源公司Item Bean
 *
 * @author jimmy_chou
 */
@Controller
@Scope("request")
public class SourceCompanyBean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 7982020681303569244L;

    /**
     * 取得來源公司SelectItems
     */
    public List<SelectItem> getSourceCompanyItems() {
        return SourceCompanySetting.getSourceCompanyItems();
    }
}

work-connect/src/main/java/com/cy/work/connect/web/view/Setting10Bean.java
package com.cy.work.connect.web.view;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.model.SelectItem;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.common.exception.UserMessageException;
import com.cy.work.common.utils.WkOrgTransMappingUtils;
import com.cy.work.common.utils.WkStringUtils;
import com.cy.work.connect.logic.manager.WCTransManager;
import com.cy.work.connect.logic.vo.view.setting11.SettingOrgTransPageVO;
import com.cy.work.connect.web.util.pf.DisplayController;
import com.cy.work.connect.web.util.pf.MessagesUtils;
import com.cy.work.connect.web.view.setting10DepSettingCheck.Setting10DepSettingCheckLogic;
import com.google.common.collect.Lists;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

/**
 * 組織異動-設定檢查 MBean
 * 
 * @author allen1214_wu
 */
@Slf4j
@NoArgsConstructor
@Controller
@Scope("view")
public class Setting10Bean implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -5234406249113205909L;

    // ========================================================================
    // 服務
    // ========================================================================
    @Autowired
    private SessionTimerBean sessionTimerBean;
    @Autowired
    private DisplayController displayController;
    @Autowired
    private transient WCTransManager transManager;
    @Autowired
    private Setting10DepSettingCheckLogic setting10DepSettingCheckLogic;

    // ========================================================================
    // view
    // ========================================================================

    @Getter
    @Setter
    private SettingOrgTransPageVO pageVO;

    /**
     * 生效日下拉選項
     */
    @Getter
    private List<SelectItem> allEffectiveDateItems;

    /**
     * 是否為有效頁面
     */
    private Boolean isActiveView = Boolean.FALSE;

    // ========================================================================
    // 方法
    // ========================================================================
    @PostConstruct
    public void init() {
        // ====================================
        // 本頁VO初始化
        // ====================================
        this.pageVO = new SettingOrgTransPageVO();

        // 準備生效日列表生效日
        this.prepareSelectItem();
        // 查詢設定資料中，最大的生效日
        if (WkStringUtils.notEmpty(this.allEffectiveDateItems)) {
            // 取日期最近的一筆
            this.pageVO.setQryEffectiveDate((Long) this.allEffectiveDateItems.get(0).getValue());
        }

        // ====================================
        // 查詢
        // ====================================
        this.btnSearchWorkVerify();
    }

    public void prepareSelectItem() {
        this.allEffectiveDateItems = Lists.newArrayList();

        // 查詢所有的生效日
        List<Date> allEffectiveDate = WkOrgTransMappingUtils.getInstance().findOrgTransMappingEffectiveDates(SecurityFacade.getCompanyId());
        if (WkStringUtils.isEmpty(allEffectiveDate)) {
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        for (Date date : allEffectiveDate) {
            this.allEffectiveDateItems.add(new SelectItem(date.getTime(), sdf.format(date)));
        }
    }

    /**
     * 有效頁面
     */
    public void viewAction() {
        this.isActiveView = Boolean.TRUE;
    }

    /**
     * 事件後觸發
     */
    public void preRenderView() {
        if (!this.isActiveView) {
            this.displayController.showPfWidgetVar("dlgIdleSession");
            return;
        }
        this.sessionTimerBean.reStartIdle();
    }

    /**
     * 查詢轉換單位設定資料
     */
    public void btnSearchWorkVerify() {

        try {
            // ====================================
            // 查詢轉換單位設定資料
            // ====================================
            this.transManager.btnSearchWorkVerify(this.pageVO, SecurityFacade.getCompanyId());

            // 準備筆數資訊
            this.setting10DepSettingCheckLogic.prepareCountInfo(this.pageVO.getVerifyDtVOList());

            this.displayController.execute("removeElmClass('spec_RemoveCss', 'ui-panelgrid')");
            this.displayController.clearFilter("screen_view_wv");
            

        } catch (UserMessageException e) {
            MessagesUtils.show(e);
            return;
        } catch (Exception e) {
            String errMsg = "查詢時發生錯誤：" + e.getMessage();
            log.error(errMsg, e);
            MessagesUtils.showError(errMsg);
            return;
        }
    }
}

work-connect/src/main/java/com/cy/work/connect/web/view/Setting11Bean.java
package com.cy.work.connect.web.view;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.common.utils.WkOrgTransMappingUtils;
import com.cy.work.common.utils.WkStringUtils;
import com.cy.work.connect.logic.manager.WCTransManager;
import com.cy.work.connect.logic.vo.view.setting11.SettingOrgTransPageVO;
import com.cy.work.connect.web.util.pf.DisplayController;
import com.cy.work.connect.web.util.pf.MessagesUtils;
import com.cy.work.connect.web.view.components.Setting11ExecDepComponent;
import com.cy.work.connect.web.view.components.Setting11TransDepComponent;
import com.google.common.collect.Lists;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 組織異動轉換管理 MBean
 *
 * @author jimmy_chou
 */
@Slf4j
@NoArgsConstructor
@Controller
@Scope("view")
@ManagedBean
public class Setting11Bean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -2354224821585616989L;

    @Getter
    @Setter
    private SettingOrgTransPageVO pageVO;
    
    /**
     * 生效日下拉選項
     */
    @Getter
    private List<SelectItem> allEffectiveDateItems;

    /**
     * 是否為有效頁面
     */
    private Boolean isActiveView = Boolean.FALSE;

    @Autowired
    private SessionTimerBean sessionTimerBean;
    @Autowired
    private DisplayController displayController;
    @Autowired
    private transient WCTransManager transManager;

    /**
     * 執行單位轉檔 component
     */
    @Getter
    @Setter
    private Setting11ExecDepComponent execDepComponent;

    /**
     * 指派單位轉檔 component
     */
    @Getter
    @Setter
    private Setting11TransDepComponent transDepComponent;

    /**
     * view 顯示錯誤訊息
     */
    @Getter
    private String errorMessage;

    @PostConstruct
    public void init() {
        // ====================================
        // 本頁VO初始化
        // ====================================
        this.pageVO = new SettingOrgTransPageVO();
        
        // 準備生效日列表生效日
        this.prepareSelectItem();
        // 查詢設定資料中，最大的生效日
        if (WkStringUtils.notEmpty(this.allEffectiveDateItems)) {
            // 取日期最近的一筆
            this.pageVO.setQryEffectiveDate((Long) this.allEffectiveDateItems.get(0).getValue());
        }

        // ====================================
        // Component 初始化
        // ====================================
        this.execDepComponent = new Setting11ExecDepComponent();
        this.transDepComponent = new Setting11TransDepComponent();
        // ====================================
        // 查詢
        // ====================================
        this.btnSearchWorkVerify();
    }
    
    public void prepareSelectItem() {
        this.allEffectiveDateItems = Lists.newArrayList();

        // 查詢所有的生效日
        List<Date> allEffectiveDate =  WkOrgTransMappingUtils.getInstance().findOrgTransMappingEffectiveDates(SecurityFacade.getCompanyId());
        if (WkStringUtils.isEmpty(allEffectiveDate)) {
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        for (Date date : allEffectiveDate) {
            this.allEffectiveDateItems.add(new SelectItem(date.getTime(), sdf.format(date)));
        }
    }

    /**
     * 有效頁面
     */
    public void viewAction() {
        this.isActiveView = Boolean.TRUE;
    }

    /**
     * 事件後觸發
     */
    public void preRenderView() {
        if (!this.isActiveView) {
            this.displayController.showPfWidgetVar("dlgIdleSession");
            return;
        }
        this.sessionTimerBean.reStartIdle();
    }

    /**
     * 查詢轉換單位設定資料
     */
    public void btnSearchWorkVerify() {

        try {
            // ====================================
            // 查詢轉換單位設定資料
            // ====================================
            this.transManager.btnSearchWorkVerify(this.pageVO, SecurityFacade.getCompanyId());

            this.displayController.execute("removeElmClass('spec_RemoveCss', 'ui-panelgrid')");

        } catch (Exception e) {
            String errMsg = "查詢時發生錯誤：" + e.getMessage();
            log.error(errMsg, e);
            MessagesUtils.showError(errMsg);
        }
    }
}

work-connect/src/main/java/com/cy/work/connect/web/view/Setting1Bean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cy.work.connect.web.view;

import com.cy.security.utils.SecurityFacade;
import com.cy.work.connect.logic.vo.view.WorkFunItemGroupVO;
import com.cy.work.connect.vo.enums.WCFuncGroupBaseType;
import com.cy.work.connect.web.logic.components.WCHomeLogicComponents;
import com.cy.work.connect.web.logic.components.WCHomepageFavoriteLogicComponents;
import com.cy.work.connect.web.util.pf.DisplayController;
import com.cy.work.connect.web.view.vo.OrgViewVo;
import com.cy.work.connect.web.view.vo.UserViewVO;
import com.cy.work.connect.web.view.vo.WCHomepageFavoriteVO;
import com.google.common.collect.Lists;
import java.io.Serializable;
import java.util.List;
import java.util.stream.Collectors;
import javax.annotation.PostConstruct;
import javax.faces.model.SelectItem;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 * 報表快選區設定 MBean
 *
 * @author brain0925_liao
 */
@Controller
@Scope("view")
@Slf4j
public class Setting1Bean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 4703183043671084716L;

    @Getter
    private String errorMessage;
    @Getter
    private UserViewVO userViewVO;
    @Getter
    private OrgViewVo depViewVo;
    @Getter
    private OrgViewVo compViewVo;

    @Getter
    /** 報表選項 */
    private List<SelectItem> reportItems;

    private List<WCHomepageFavoriteVO> reports;
    /**
     * 選取的報表快選
     */
    @Setter
    @Getter
    private List<String> selectReportTypes = Lists.newArrayList();

    @Autowired
    private WCHomeLogicComponents wcHomeLogicComponents;
    @Autowired
    private WCHomepageFavoriteLogicComponents wcHomepageFavoriteLogicComponents;

    @PostConstruct
    public void init() {
        userViewVO = new UserViewVO(SecurityFacade.getUserSid());
        depViewVo = new OrgViewVo(SecurityFacade.getPrimaryOrgSid());
        compViewVo = new OrgViewVo(SecurityFacade.getCompanySid());
        initItmes();
        initDefault();
    }

    private void initItmes() {
        reportItems = Lists.newArrayList();
        reports = Lists.newArrayList();
        List<WorkFunItemGroupVO> workFunItemGroups =
            wcHomeLogicComponents.getWorkFunItemGroupByTypeAndUserPermission(
                WCFuncGroupBaseType.SEARCH.getKey(), userViewVO.getSid(), depViewVo.getSid());
        try {

            workFunItemGroups
                .get(0)
                .getWorkFunItemVOs()
                .forEach(
                    item -> {
                        reports.add(
                            new WCHomepageFavoriteVO(item.getUrl(), item.getFunction_title()));
                        SelectItem si = new SelectItem(item.getUrl(), item.getFunction_title());
                        reportItems.add(si);
                    });
        } catch (Exception e) {
            log.warn("initItmes", e);
        }
    }

    private void initDefault() {
        selectReportTypes = Lists.newArrayList();

        try {
            wcHomepageFavoriteLogicComponents
                .getWCHomepageFavoriteVOByUserSid(userViewVO.getSid())
                .forEach(
                    item -> {
                        selectReportTypes.add(item.getPagePath());
                    });
        } catch (Exception e) {
            log.warn("initDefault", e);
        }
    }

    public void saveSetting() {
        try {
            List<WCHomepageFavoriteVO> wcHomepageFavoriteVO = Lists.newArrayList();
            selectReportTypes.forEach(
                item -> {
                    List<WCHomepageFavoriteVO> sel =
                        reports.stream()
                            .filter(each -> each.getPagePath().equals(item))
                            .collect(Collectors.toList());
                    wcHomepageFavoriteVO.add(sel.get(0));
                });
            wcHomepageFavoriteLogicComponents.saveWCHomepageFavorite(
                wcHomepageFavoriteVO, userViewVO.getSid());
        } catch (Exception e) {
            log.warn("saveSetting", e);
            errorMessage = e.getMessage();
            DisplayController.getInstance().update("confimDlgTemplate");
            DisplayController.getInstance().showPfWidgetVar("confimDlgTemplate");
        }
    }
}

work-connect/src/main/webapp/setting/setting3_categoryTag.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:p="http://primefaces.org/ui"
        xmlns:f="http://xmlns.jcp.org/jsf/core">

    <!-- ====================================== -->
    <!-- 維護內容 -->
    <!-- ====================================== -->
    <p:panelGrid>
        <p:row>
            <p:column colspan="1">
                <p:outputLabel value="類別" styleClass="column-label-require"/>
            </p:column>
            <p:column colspan="1">
                <p:inputTextarea
                        id="editCategoryName"
                        value="#{setting3Bean.categoryTagEditVO.categoryName}"
                        rows="1"
                        cols="30"/>
            </p:column>
        </p:row>
        <p:row rendered="false">
            <p:column colspan="1">
                <p:outputLabel value="排序序號"/>
            </p:column>
            <p:column colspan="1">
                <p:inputTextarea
                        value="#{setting3Bean.categoryTagEditVO.seq}"
                        rows="1"
                        cols="15"/>
            </p:column>
        </p:row>
        <p:row>
            <p:column colspan="1">
                <p:outputLabel value="使用狀態"/>
            </p:column>
            <p:column colspan="1">
                <p:selectOneMenu id="editCategoryStatus"
                                 value="#{setting3Bean.categoryTagEditVO.status}">
                    <f:selectItems value="#{activationItemBean.activationItems}"/>
                </p:selectOneMenu>
            </p:column>
        </p:row>

        <p:row style="vertical-align: top">
            <p:column colspan="1">
                <p:outputLabel value="備註"/>
            </p:column>
            <p:column colspan="1">
                <p:inputTextarea
                        value="#{setting3Bean.categoryTagEditVO.memo}"
                        rows="5"
                        cols="30"/>
            </p:column>
        </p:row>
    </p:panelGrid>
</ui:composition>
    

work-connect/src/main/webapp/setting/setting8.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
        xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        template="../template/templateProject.xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:p="http://primefaces.org/ui"
        xmlns:cp="http://java.sun.com/jsf/composite/components"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
>
    <f:metadata>
        <f:event
                type="preRenderView"
                listener="#{sessionTimerBean.reStartIdle()}"/>
    </f:metadata>

    <ui:define name="title">
        <h:outputText value="項目批次匯入"/>
    </ui:define>

    <ui:define name="content">
        <style>
            /*colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4']*/
            .colorType_CategoryTag {
                background: #CCFFFF
            }

            .colorType_MenuTag {
                background: #CCFFCC
            }

            .colorType_Tag {
                background: #CCCCFF
            }

            .colorType_EXEC_TRANS_DEP {
                background: #DDDF00
            }
        </style>
        <script type="text/javascript">
            //<![CDATA[
            // ]]>
        </script>
        <p:outputPanel id="allPanel">
            <p:panel
                    id="headerTitle"
                    style="border:none">
                <p:panelGrid
                        style="width:100%;"
                        id="searchArea">
                    <p:row>
                        <p:column style="text-align:right;width:80px;">
                            <p:outputLabel value="來源公司：" styleClass="column-label-require"/>
                        </p:column>
                        <p:column
                                style="text-align:left;"
                                colspan="2">
                            <p:selectOneMenu
                                    value="#{setting8Bean.searchComponent.searchVo.sourceCompany}">
                                <f:selectItem
                                        itemLabel="請選擇"
                                        itemValue=""/>
                                <f:selectItems value="#{sourceCompanyBean.sourceCompanyItems}"/>
                                <p:ajax event="change" process="@this" update="@this"/>
                            </p:selectOneMenu>
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column style="text-align:right;">
                            <p:outputLabel value="目的公司："/>
                        </p:column>
                        <p:column>
                            <p:selectOneMenu
                                    value="#{setting8Bean.searchComponent.searchVo.importCompany}"
                                    disabled="true">
                                <f:selectItem
                                        itemLabel="請選擇"
                                        itemValue=""/>
                                <f:selectItems value="#{companyBean.companyItems}"/>
                                <p:ajax event="change" listener="#{setting8Bean.loadALLTags()}"
                                        process="@this" update="id_queryResult searchArea"/>
                            </p:selectOneMenu>
                        </p:column>
                        <p:column>
                            <p:panelGrid columns="12">
                                <p:commandButton
                                        title="複製來源公司挑選類別"
                                        value="複製"
                                        onstart="showLoad();"
                                        oncomplete="hideLoad();"
                                        actionListener="#{setting8Bean.copyTag()}"
                                        process="@this searchArea"/>
                                <p:commandButton
                                        title="初始畫面"
                                        value="清除"
                                        onstart="showLoad();"
                                        oncomplete="hideLoad();"
                                        actionListener="#{setting8Bean.init()}"
                                        update="searchArea id_queryResult"
                                        process="@this"/>
                                <p:commandButton
                                        title="刪除目的公司勾選項目"
                                        value="刪除"
                                        actionListener="#{setting8Bean.deleteTag()}"
                                        update="searchArea id_queryResult"
                                        onstart="showLoad();"
                                        oncomplete="hideLoad();"
                                        process="@this searchArea id_queryResult"/>
                            </p:panelGrid>
                        </p:column>
                    </p:row>
                    <p:row>
                        <p:column style="text-align:right;">
                            <p:outputLabel value="挑選複製類別：" styleClass="column-label-require"/>
                        </p:column>
                        <p:column style="text-align:left;">
                            <p:commandButton
                                    icon="fa fa-gear"
                                    actionListener="#{setting8Bean.searchComponent.loadTags()}"
                                    update="tagDialogPanel"
                                    onstart="showLoad();"
                                    process="@this"
                                    oncomplete="hideLoad();"/>
                        </p:column>
                    </p:row>
                    <p:row rendered="#{not empty setting8Bean.searchComponent.searchVo.importCompany and setting8Bean.allTagTreeManager.rootNode.childCount > 0}">
                        <p:column style="text-align:right;">
                            <p:outputLabel value="全選："/>
                        </p:column>
                        <p:column style="text-align:left;">
                            <p:selectBooleanCheckbox
                                    widgetVar="tagCheckAll"
                                    value="#{setting8Bean.allTagTreeManager.checkAll}">
                                <p:ajax event="change"
                                        listener="#{setting8Bean.allTagTreeManager.selectAllTree()}"
                                        process="@this" update="id_queryResult"/>
                            </p:selectBooleanCheckbox>
                        </p:column>
                    </p:row>
                </p:panelGrid>

                <!--查詢表身-->
                <p:treeTable
                        id="id_queryResult"
                        widgetVar="wv_queryResult"
                        value="#{setting8Bean.allTagTreeManager.rootNode}"
                        var="node"
                        nodeVar="item"
                        resizableColumns="false"
                        selectionMode="multiple"
                        selection="#{setting8Bean.allTagTreeManager.selNode}"
                        rowStyleClass="colorType_#{item.type}"
                        emptyMessage="無符合資料"
                        scrollable="true"
                        scrollHeight="475"
                        tableStyle="width:99%">
                    <f:facet name="header">
                        項目批次匯入－目的公司現況
                    </f:facet>
                    <p:ajax event="select" process="@this" update="id_queryResult"/>
                    <p:ajax event="unselect" process="@this" update="id_queryResult"/>
                    <p:column headerText="類別">
                        <h:outputText value="#{node.categoryName}"
                                      style=" #{node.status eq 'INACTIVE'?'color: red':''}"/>
                    </p:column>
                    <p:column headerText="單據名稱">
                        <h:outputText value="#{node.menuName}"
                                      style=" #{node.status eq 'INACTIVE'?'color: red':''}"/>
                    </p:column>
                    <p:column headerText="執行項目">
                        <h:outputText value="#{node.name}"
                                      style=" #{node.status eq 'INACTIVE'?'color: red':''}"/>
                    </p:column>
                    <p:column headerText="刪除" style="text-align:center;">
                        <p:selectBooleanCheckbox value="#{item.selected}">
                            <p:ajax event="change"
                                    listener="#{setting8Bean.allTagTreeManager.selectNode(item)}"
                                    process="@this" update="id_queryResult"/>
                        </p:selectBooleanCheckbox>
                    </p:column>
                </p:treeTable>
            </p:panel>
        </p:outputPanel>

        <!-- ====================================== -->
        <!-- 查詢 - 挑選類別 dialog -->
        <!-- ====================================== -->
        <p:dialog header="挑選類別" widgetVar="tagUnitDlg" modal="true" resizable="false">
            <p:outputPanel id="tagDialogPanel">
                <cp:tagTree model="#{setting8Bean.searchComponent.tagTreeManager}"
                            dlgName="tagUnitDlg" btnShow="true">
                    <f:actionListener for="actionEvent"
                                      binding="#{setting8Bean.searchComponent.saveTag()}"/>
                </cp:tagTree>
            </p:outputPanel>
        </p:dialog>
    </ui:define>
</ui:composition>